from fastapi import APIRouter
from pydantic import BaseModel

from services.parser import extract_text
from services.resume_parser_ai import (
    extract_resume_details
)

from services.ollama_resume import (
    generate_resume
)

from services.resume_builder import (
    build_resume
)

router = APIRouter()

class AutoResumeRequest(BaseModel):

    filename: str
    job_description: str

@router.post("/")
def auto_resume(req: AutoResumeRequest):

    filepath = f"uploads/{req.filename}"

    resume_text = extract_text(
        filepath
    )

    details = extract_resume_details(
        resume_text
    )

    ats_resume = generate_resume(
        resume_text,
        req.job_description
    )

    build_resume(
        name="Candidate",
        email=details["email"],
        phone=details["phone"],
        summary=ats_resume,
        skills="Generated by AI",
        projects="Generated by AI",
        education="Generated by AI",
        output_file="generated/ats_resume.pdf"
    )

    return {
        "message": "ATS Resume Generated",
        "file": "ats_resume.pdf"
    }
